Repository googleworkspace/node-samples, pull requests merged in 2022-07, with the labels that each got.

#191 chore: standardize workflows
  .github/workflows/lint.yaml
  .github/workflows/lint.yml
Labels: yaml

#192 chore: add license headers
  .eslintrc.js
  .github/snippet-bot.yml
  drive/snippets/setup.sh
  drive/snippets/test.sh
  sheets/snippets/setup.sh
  sheets/snippets/test.sh
  slides/snippets/setup.sh
  slides/snippets/slides_text_style_update.js
  slides/snippets/test.sh
Labels: shell

#197 Fix: Update parents value in upload_to_folder.js
  drive/snippets/drive_v3/file_snippets/upload_to_folder.js
Labels: javascript
